# Uncomment this line to define a global platform for your project
 platform :ios, '9.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'Remote' do
    pod 'Firebase', '>= 2.5.0'
end

target 'RemoteTests' do

end

target 'RemoteUITests' do

end

